#!/usr/bin/env bash
# checking for command line arguments

if [ $# -  lt 4 ]; 
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
        exit 1
fi

# assigning parameters to variable

path_to_file=$1
ip=$2
username+$2
path_to_ssh_key=$4

#DISABLING STRICT HOST KEY CHECKING

SCP -0 "StrictHostKeyChecking=no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"


# checking if the transfer was succesful
if [ $? -eq 0]
then
	echo "FILE WAS TRANSFERED SUCESSFULLY"
else
        echo "FILE TRANSFER FAILED"
fi
